/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAuthenticatedRouteImport } from './routes/_authenticated/_authenticated'
import { Route as AuthenticatedAuthenticatedUserRouteImport } from './routes/_authenticated/_authenticated.user'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuthenticatedRoute =
  AuthenticatedAuthenticatedRouteImport.update({
    id: '/_authenticated/_authenticated',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAuthenticatedUserRoute =
  AuthenticatedAuthenticatedUserRouteImport.update({
    id: '/user',
    path: '/user',
    getParentRoute: () => AuthenticatedAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof AuthenticatedAuthenticatedUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/user': typeof AuthenticatedAuthenticatedUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_authenticated': typeof AuthenticatedAuthenticatedRouteWithChildren
  '/_authenticated/_authenticated/user': typeof AuthenticatedAuthenticatedUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/user'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/_authenticated/_authenticated'
    | '/_authenticated/_authenticated/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthenticatedAuthenticatedRoute: typeof AuthenticatedAuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_authenticated': {
      id: '/_authenticated/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_authenticated/user': {
      id: '/_authenticated/_authenticated/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthenticatedAuthenticatedUserRouteImport
      parentRoute: typeof AuthenticatedAuthenticatedRoute
    }
  }
}

interface AuthenticatedAuthenticatedRouteChildren {
  AuthenticatedAuthenticatedUserRoute: typeof AuthenticatedAuthenticatedUserRoute
}

const AuthenticatedAuthenticatedRouteChildren: AuthenticatedAuthenticatedRouteChildren =
  {
    AuthenticatedAuthenticatedUserRoute: AuthenticatedAuthenticatedUserRoute,
  }

const AuthenticatedAuthenticatedRouteWithChildren =
  AuthenticatedAuthenticatedRoute._addFileChildren(
    AuthenticatedAuthenticatedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthenticatedAuthenticatedRoute: AuthenticatedAuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
